- edx-platform/wikilearn/lms/static/sass/features/_messenger.scss
Fix margin and styling for chat app.
> Fix chat styling

- edx-platform/wikilearn/lms/templates/course.html
- edx-platform/wikilearn/lms/templates/index.html
Course description added and hide banner's description
> Course description added and hide banner's description

- edx-platform/wikilearn/lms/static/sass/base/_spinner.scss
- edx-platform/wikilearn/lms/static/sass/features/_messenger.scss
- edx-platform/wikilearn/lms/static/sass/partials/lms/theme/_extras.scss
- edx-platform/wikilearn/lms/templates/main.html
Messenger UI implementation and enhancement
**Before**
**After**
> Messenger UI implementation and enhancement

- edx-platform/wikilearn/lms/templates/ace_common/edx_ace/common/base_body.html
Add base body html in theme.
Related edx PR: https://github.com/wikimedia/edx-platform/pull/9
> Add base body email

- edx-platform/wikilearn/lms/templates/header/navbar-authenticated.html
Add Messenger and Reports tab to Nav bar.
> Add Messenger and Report tab in navbar

- edx-platform/wikilearn/lms/templates/student/edx_ace/accountactivation/email/body.html
- edx-platform/wikilearn/lms/templates/student/edx_ace/accountactivation/email/body.txt
Add activation email html changes.
> Override Account Activation email template

- edx-platform/wikilearn/lms/static/sass/features/_messenger.scss
Styles feedback for messenger implementation.
> Styles feedback for messenger implementation

- edx-platform/wikilearn/lms/templates/header/navbar-authenticated.html
Update tab names 
- Messenger -> Inbox
- Discover New -> Catalog
> Update tab names in navbar

- edx-platform/wikilearn/lms/static/sass/features/_messenger.scss
Inbox design feedback implementation
> Inbox design feedback implementation

- edx-platform/wikilearn/lms/templates/footer.html
- edx-platform/wikilearn/lms/templates/header/navbar-not-authenticated.html
> Links for header and footer

- edx-platform/wikilearn/lms/templates/footer.html
- edx-platform/wikilearn/lms/templates/header/navbar-not-authenticated.html
- Add links for header and footer
> Stage release for updated URL(s) 05-01-2021

- edx-platform/wikilearn/cms/static/js/index.js
- edx-platform/wikilearn/cms/static/js/views/course_rerun.js
- edx-platform/wikilearn/cms/templates/course-create-rerun.html
- edx-platform/wikilearn/cms/templates/index.html
Related edx branch: https://github.com/wikimedia/edx-platform/pull/46
> record course translation

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_extras.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- edx-platform/wikilearn/lms/static/sass/partials/lms/theme/_certificates.scss
Includes the styles for approve translations
> Multilingual Feature -> Approve Translations

- edx-platform/wikilearn/cms/templates/index.html
https://github.com/wikimedia/edx-platform/pull/107
> Add send/fetch Api buttons controlled from admin panel

- edx-platform/wikilearn/cms/templates/course-create-rerun.html
Related edX PR: https://github.com/wikimedia/edx-platform/pull/122
> Add checks in trnalsated rerun creation and show relevant errors

- edx-platform/wikilearn/cms/templates/widgets/header.html
> Add meta translations page to studio navbar in header.html

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
> Multilingual Feature -> UI fixes

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
> Multilingual Feature -> Update badge styling

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- #46 
- #47 
https://github.com/wikimedia/edx-platform/pull/144
> Stage Release 30-06-2022 (Wikimedia - Phase 2 - Fix Version Reports + Add Badges on Studio)

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- edx-platform/wikilearn/lms/templates/header/user_dropdown.html
- #49 
- #50 
https://github.com/wikimedia/edx-platform/pull/149
> Stage Release 15-07-2022 (Wikimedia - Phase 2 - Fix Truncate Username + Fix Applied Badge Cursor)

- edx-platform/wikilearn/cms/static/sass/components/_header.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_extras.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_variable.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_variables-v1.scss
- edx-platform/wikilearn/cms/templates/widgets/header.html
- edx-platform/wikilearn/lms/static/sass/components/_header.scss
- edx-platform/wikilearn/lms/templates/header/user_dropdown.html
- edx-platform/wikilearn/lms/templates/main.html
> Make studio header same as LMS

- edx-platform/wikilearn/lms/static/sass/features/_progress-page.scss
- edx-platform/wikilearn/lms/static/sass/partials/lms/theme/_extras.scss
> Customise Progress View

- edx-platform/wikilearn/lms/templates/header/navbar-authenticated.html
> Add sysadmin in lms navbar

- edx-platform/wikilearn/cms/static/sass/components/_header.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_extras.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_variable.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_variables-v1.scss
- edx-platform/wikilearn/cms/templates/widgets/header.html
- edx-platform/wikilearn/lms/static/sass/components/_header.scss
- edx-platform/wikilearn/lms/static/sass/features/_progress-page.scss
- edx-platform/wikilearn/lms/static/sass/partials/lms/theme/_extras.scss
- edx-platform/wikilearn/lms/templates/header/user_dropdown.html
- edx-platform/wikilearn/lms/templates/main.html
- #53 
- #54 
- #56 
- https://github.com/wikimedia/edx-platform/pull/157
> Stage Release 27-07-2022 (Wikimedia - Phase 2 - Update Studio Header + Add Sysadmin)

- edx-platform/wikilearn/lms/lms/templates/courseware/progress.html
- edx-platform/wikilearn/lms/templates/courseware/course_navigation.html
- edx-platform/wikilearn/lms/templates/courseware/tabs.html
https://github.com/wikimedia/edx-platform/pull/156
> Rename course tabs 'Progress' -> 'Score', 'Wiki Progress' -> 'Progress'

- edx-platform/wikilearn/lms/lms/templates/courseware/progress.html
- edx-platform/wikilearn/lms/templates/courseware/course_navigation.html
- edx-platform/wikilearn/lms/templates/courseware/tabs.html
- edx-platform/wikilearn/lms/templates/header/navbar-authenticated.html
- #55 
- https://github.com/wikimedia/edx-platform/pull/159
> Stage Release 28-07-2022 - Add custom course progress tab

- edx-platform/wikilearn/lms/static/sass/components/_header.scss
- edx-platform/wikilearn/lms/static/sass/features/_landing.scss
> Make studio header same as LMS QA Feedback

- edx-platform/wikilearn/lms/templates/footer.html
[WM-169](https://edlyio.atlassian.net/browse/WM-169)
> update privacy policy links

- edx-platform/wikilearn/lms/static/sass/components/_header.scss
- edx-platform/wikilearn/lms/static/sass/features/_landing.scss
- edx-platform/wikilearn/lms/templates/footer.html
- #60 
- #61 
- https://github.com/wikimedia/edx-platform/pull/163
> Stage Release 07-09-2022 - Update Studio Header and Privacy Policy Link

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- edx-platform/wikilearn/lms/static/sass/features/_messenger.scss
> Make lms & studio responsive for right-to-left languages

- edx-platform/wikilearn/cms/static/sass/components/_header.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- edx-platform/wikilearn/lms/static/sass/base/_reset.scss
- edx-platform/wikilearn/lms/static/sass/components/_course.scss
- edx-platform/wikilearn/lms/static/sass/components/_header.scss
- edx-platform/wikilearn/lms/static/sass/features/_messenger.scss
- edx-platform/wikilearn/lms/templates/footer.html
- edx-platform/wikilearn/lms/templates/index.html
- #66
- #67 
- https://github.com/wikimedia/edx-platform/pull/176
> Stage Release 14-10-2022 (Wikimedia - RTL fixes)

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- edx-platform/wikilearn/lms/static/sass/features/_landing.scss
> Stage Release 27-10-2022 (Wikimedia - RTL fixes)

- edx-platform/wikilearn/cms/static/sass/components/_header.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- edx-platform/wikilearn/lms/static/sass/base/_reset.scss
- edx-platform/wikilearn/lms/static/sass/components/_course.scss
- edx-platform/wikilearn/lms/static/sass/components/_header.scss
- edx-platform/wikilearn/lms/static/sass/features/_messenger.scss
- edx-platform/wikilearn/lms/templates/index.html
- #74 
- #75 
- #76 
- https://github.com/wikimedia/edx-platform/pull/204
> Stage Release 16-11-2022 (Wikimedia - LMS and Studio Font Customization) 

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_discover_courses.scss
> Stage Release 01-12-2022 (Wikimidia - Discove Course Fixes)

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_discover_courses.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_extras.scss
- #87 
- https://github.com/wikimedia/edx-platform/pull/235
> Prod Release 16-12-2022 (Wikimedia - Page Title Styling)

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_discover_courses.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- #89 
- https://github.com/wikimedia/edx-platform/pull/245
> Stage Release 30-01-22 (Section Headers Styling)

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_discover_courses.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- #90 
- https://github.com/wikimedia/edx-platform/pull/252
> Prod Release 31-01-23 (Headers styling)

- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_custom-fonts.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_translations.scss
- edx-platform/wikilearn/cms/static/sass/partials/cms/theme/_variable.scss
- edx-platform/wikilearn/lms/static/sass/partials/lms/theme/_custom-fonts.scss
- edx-platform/wikilearn/lms/static/sass/partials/lms/theme/_variables.scss
- #92 
- https://github.com/wikimedia/edx-platform/pull/279
> Stage Release 27-03-2023 (Add Montserrat and Source Sans Pro fonts) #278

- edx-platform/wikilearn/lms/static/sass/components/_course.scss
Description:
Add styling for HTML images
> Fix html image styling
